version: "3"

services:
  db:
    container_name: postgres
    networks:
      default:
      aifuku-network:
        aliases:
          - postgres-container
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    tty: true
    restart: always

  nuxt:
    container_name: nuxt
    networks:
      default:
      aifuku-network:
        aliases:
          - nuxt-container
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - ./src/frontend:/work
    tty: true
    restart: always

  backend:
    container_name: backend
    networks:
      default:
      aifuku-network:
        aliases:
          - backend-container
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "3001:3000"
      - "5555:5555"
    volumes:
      - ./src/backend:/work
    tty: true
    restart: always

networks:
  aifuku-network:
    external: true
