version: "3"

services:
  db:
    container_name: postgres
    image: postgres:15.3-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    tty: true

  express:
    container_name: express
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./src/backend:/app
    tty: true

  nuxt:
    container_name: nuxt
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3001:3000"
    volumes:
      - ./src/frontend:/app
    tty: true
