version: "3"
services:
  express:
    container_name: express
    build:
      context: .
      dockerfile: ./docker/Dockerfile.express
    ports:
      - "3000:3000"
    volumes:
      - ./src/backend:/app
    tty: true