export const VALIDATION_ERRORS = {
  INVALID_EMAIL: 'メールアドレスの形式を満たしていません',
  INVALID_PASSWORD_LOWER_LETTER_REQUIRED: '小文字を含めてください',
  INVALID_PASSWORD_UPPER_LETTER_REQUIRED: '大文字を含めてください',
  INVALID_PASSWORD_NUMBER_REQUIRED: '数字を含めてください',
  INVALID_PASSWORD_SPECIAL_CHARACTER_REQUIRED: '記号を含めてください',
  INVALID_PASSWORD_UNUSABLE_CHARACTER: '使用できない文字が含まれています',
  INVALID_PASSWORD_NOT_ENOUGH_LENGTH: '文字数が足りません',
  REQUIRED: '必ず入力してください',
  NOT_MATCH_PASSWORD: '入力されたパスワードが一致しません',
}
